In [3]:
import numpy as np

1. Buatlah suatu tensor ddibawah ini dengan python

In [4]:
Tensor = np.array([
    [[23, 50], [7, 12]],
    [[57, 67], [99, 43]],
    [[75, 21], [57, 12]],
    [[87, 26], [18, 84]]
])
Tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

2. Lakukan perkalian terhadap Matrix berikut

In [5]:
A = np.array([
    [23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]
])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [7]:
B = np.array([17, 22, 19])
B

array([17, 22, 19])

In [10]:
A @ B

array([1852, 2454, 4305])

3. Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini

In [13]:
A = np.array([
    [23, 50, 19],
    [7, 12, 109],
    [57, 67, 98]
])
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [14]:
#Transpose
A.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [18]:
from numpy.linalg import inv, det

In [21]:
#Determinan
np.linalg.det(A)

131344.0000000002

In [22]:
#Invers
np.linalg.inv(A)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])