# Non Graded Challange 6
Non Graded Assignment ini dibuat guna mengevaluasi pembelajaran pada Hacktiv8 Data Science Fulltime Program ini khususnya pada konsep **Eigen de Composition**.

## Problem

Apakah B adalah eigenvector dari A? Jika iya berapakah eigenvaluenya?  
A =   
[[1, -1],  
[6, -4]]  
B = [1, 3] 

## Answer

In [10]:
import numpy as np
from numpy.linalg import inv, det, eig

In [11]:
A = np.array([
    [1, -1],
    [6, 4]
])
A

array([[ 1, -1],
       [ 6,  4]])

In [12]:
B = np.array([1, 3])
B

array([1, 3])

In [13]:
eigval, eigvec = eig(A)

In [18]:
eigvec == B

array([[False, False],
       [False, False]])

B bukan merupakan eigenvector dari A

In [15]:
eigval

array([2.5+1.93649167j, 2.5-1.93649167j])

In [16]:
eigvec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])